@startuml
skinparam style strictuml
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "Registered\nUser" as UserReg

' This is a comment on a single line
package backend <<express:4.19.2>>{
    boundary "Publication" as PublicationDetailView << PUG >>
    boundary "mainLayoutProfile" as mainLayoutProfileView << PUG >>
    control "PublicationController\nCreatePublication" as CreatePublicationController << JavaScript >>
    control Router << JavaScript >>
    control auth << middleware >>
    control "upload.single" as uploadSingle << middleware >>
    entity Publication << JavaScript >>
}

package frontend {
    boundary "publication" as PublicationHtml << HTML >>
    boundary "output" as outputCss << CSS >>
    boundary "font-awesome" as fontCss << CSS >>
    control script << JavaScript >>
}

UserReg .r.> PublicationHtml
PublicationHtml -d-> outputCss
PublicationHtml -d-> fontCss
PublicationHtml -d-> script
PublicationHtml .r.> Router
Router -> auth
Router -d-> uploadSingle
Router -d-> CreatePublicationController
CreatePublicationController -d-> PublicationDetailView
CreatePublicationController -d-> Publication
PublicationDetailView -d-> mainLayoutProfileView: extends

@enduml