@startuml
skinparam style strictuml
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

package Analysis{
    boundary "Publication\nDetailView" as PublicationDetailViewAnalysis
    entity "Publication" as PublicationAnalysis
    control "CreatePublication\nController" as CreatePublicationControllerAnalysis
}

package Design{
    package backend {
        boundary "Publication" as PublicationDetailView << PUG >>
        boundary "mainLayoutProfile" as mainLayoutProfileView << PUG >>
        control "PublicationController\nCreatePublication" as CreatePublicationController
        control Router
        control auth << middleware >>
        control "upload.single" as uploadSingle << middleware >>
        entity PublicationModel
    }
    package frontend {
        boundary "Publication" as PublicationHtml << HTML >>
        boundary "output" as outputCss << CSS >>
        boundary "font-awesome" as fontCss << CSS >>
        control script << JavaScript >>
    }
}

PublicationDetailViewAnalysis --> CreatePublicationControllerAnalysis
CreatePublicationControllerAnalysis --> PublicationAnalysis

PublicationHtml ..> Router
PublicationHtml -d-> outputCss
PublicationHtml -d-> fontCss
PublicationHtml -d-> script
Router -> auth
Router -d-> uploadSingle
Router -d-> CreatePublicationController
CreatePublicationController -d-> PublicationDetailView
PublicationDetailView -d-> mainLayoutProfileView: extends
CreatePublicationController -d-> PublicationModel

PublicationDetailViewAnalysis .[#green].> PublicationHtml : <font color=green><<trace>></font>
PublicationDetailViewAnalysis .[#green].> outputCss : <font color=green><<trace>></font>
PublicationDetailViewAnalysis .[#green].> fontCss : <font color=green><<trace>></font>
PublicationDetailViewAnalysis .[#green].> PublicationDetailView : <font color=green><<trace>></font>

CreatePublicationControllerAnalysis .[#coral].> Router : <font color=coral><<trace>></font>
CreatePublicationControllerAnalysis .[#coral].> CreatePublicationController : <font color=coral><<trace>></font>
CreatePublicationControllerAnalysis .[#coral].> auth : <font color=coral><<trace>></font>
CreatePublicationControllerAnalysis .[#coral].> uploadSingle : <font color=coral><<trace>></font>
CreatePublicationControllerAnalysis .[#coral].> script : <font color=coral><<trace>></font>

PublicationAnalysis .[#3cdfff].> PublicationModel : <font color=3cdfff><<trace>></font>

@enduml