@startuml
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "Registered\nUser" as UserReg

boundary "Publication\nDetailView" as PublicationDetailView
entity Publication
control "CreatePublication\nController" as CreatePublicationController

UserReg --> PublicationDetailView
PublicationDetailView --> CreatePublicationController
CreatePublicationController --> Publication
@enduml