@startuml
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor Receiver

boundary "New Report" as NewReportView
entity Client
entity Vehicle
entity Report
<!-- entity Repair -->
entity Employee
entity PreviousDamage
entity ReportedProblem

control "CreateReport\nController" as CreateReportController

Receiver --> NewReportView
NewReportView --> CreateReportController
CreateReportController --> Client
CreateReportController --> Vehicle
CreateReportController --> Report
@enduml