@startuml paquete de diseño laravel
skinparam style strictuml
allow_mixing

package config {
    class "routes.rb" as webPHP #bisque {}
}

package app {
    package controllers #bisque {}
    package models #d8f9ff {}
    package views #cefad0 {}
    package mailer {}
}

package packages{
    component pagy
    component pg
    component rails
}

webPHP .d.> controllers
controllers .d-> views
controllers .d-> models
controllers .d-> packages
controllers .d-> mailer
' serverJS .d.> appJS

' appJS .d.> router
' appJS .[hidden].> db
' appJS ..> morgan
' appJS ..> cookieParser
' appJS ..> express
' appJS ..> dotenv
' appJS ..> pug
' appJS .[hidden]left.> public.view

' router .left.> public.view
' router ..> express
' router ..> middleware
' router ..> controllers
' router ..> models

' middleware ..> multer
' middleware ..> path
' middleware ..> jsonwebtoken
' middleware .left.> public.view

' controllers ..> services

' services ..> models
' services ..> nodemailer
' services ..> jsonwebtoken
' services ..> bcrypt
' services ..> view

' models ..> db
' db .right.> pg

' view .[hidden]down.> css
' css .[hidden]left.> img
' img .[hidden]left.> js

' express .[hidden]left.> morgan
' morgan .[hidden]left.> cookieParser
' cookieParser .[hidden]left.> dotenv
' dotenv .[hidden]left.> pug

' express .[hidden]down.> path
' multer .[hidden]left.> path

' multer .[hidden]down.> bcrypt
' bcrypt .[hidden]left.> nodemailer
' nodemailer .[hidden]left.> jsonwebtoken

' nodemailer .[hidden]down.> pg
@enduml