@startuml
skinparam style strictuml
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

package Analysis{
    boundary "Publication\nDetailView" as PublicationDetailViewAnalysis
    entity "Publication" as PublicationAnalysis
    control "CreatePublication\nController" as CreatePublicationControllerAnalysis

    PublicationDetailViewAnalysis --> CreatePublicationControllerAnalysis
    CreatePublicationControllerAnalysis --> PublicationAnalysis
}

package Design{
    package backend <<django:5.0.2>>{
        boundary "create_publication" as PublicationDetailView << DjangoTemplates >>
        boundary "layout" as mainLayoutProfileView << DjangoTemplates >>
        boundary "widget_tweaks" as widgetTweaks << django-widget-tweaks >>
        boundary "tailwind_tags" as tailwindTags << django-tailwind >>
        control urls << Python >>
        control "<b>@login_required</b>\npublication_views.\nregister_publication" as CreatePublicationController << Python >>
        entity PublicationForm << Python >>
        entity Publication << Python >>
    }

    package frontend {
        boundary "create_publication" as PublicationHtml << HTML >>
        boundary "tailwind_css" as outputCss << CSS >>
        control previewImage << JavaScript >>
    }

    PublicationHtml -d-> outputCss
    PublicationHtml *-d- previewImage
    PublicationHtml ..> urls
    urls --> CreatePublicationController
    CreatePublicationController -d-> PublicationDetailView
    PublicationDetailView -d-> mainLayoutProfileView: extends
    mainLayoutProfileView -> tailwindTags: load
    PublicationDetailView -> widgetTweaks: load

    CreatePublicationController -d-> PublicationForm
    PublicationForm -d-> Publication
}

'trace
PublicationDetailViewAnalysis .[#green]r.> PublicationHtml : <font color=green><<trace>></font>
PublicationDetailViewAnalysis .[#green].> outputCss : <font color=green><<trace>></font>
PublicationDetailViewAnalysis .[#green].> PublicationDetailView : <font color=green><<trace>></font>

CreatePublicationControllerAnalysis .[#coral].> urls : <font color=coral><<trace>></font>
CreatePublicationControllerAnalysis .[#coral].> CreatePublicationController : <font color=coral><<trace>></font>
CreatePublicationControllerAnalysis .[#coral].> previewImage : <font color=coral><<trace>></font>

PublicationAnalysis .[#3cdfff].> PublicationForm : <font color=3cdfff><<trace>></font>
PublicationAnalysis .[#3cdfff].> Publication : <font color=3cdfff><<trace>></font>


@enduml