@startuml
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "Registered\nUser" as UserReg

boundary "LandingPage\nView" as LandingPageView
boundary "Publication\nDetailView" as PublicationDetailView

entity Publication
entity Comment
entity User

control "ListPublication\nController" as ListPublicationController
control "CreatePublication\nController" as CreatePublicationController
control "ShowPublication\nController" as ShowPublicationController
control "EditPublication\nController" as EditPublicationController
control "DeletePublication\nController" as DeletePublicationController
control "CreateComment\nController" as CreateCommentController
control "ListComment\nController" as ListCommentController
control "EditComment\nController" as EditCommentController
control "DeleteComment\nController" as DeleteCommentController

UserReg --> LandingPageView
UserReg --> PublicationDetailView

LandingPageView --> ListPublicationController
LandingPageView --> CreatePublicationController
LandingPageView --> ShowPublicationController
PublicationDetailView --> CreatePublicationController
PublicationDetailView --> EditPublicationController
PublicationDetailView --> DeletePublicationController
PublicationDetailView --> CreateCommentController
PublicationDetailView --> ListCommentController
PublicationDetailView --> EditCommentController
PublicationDetailView --> DeleteCommentController

ListPublicationController --> User
ListPublicationController --> Publication
CreatePublicationController --> Publication
ShowPublicationController --> Publication
EditPublicationController --> Publication
DeletePublicationController --> Publication
CreateCommentController --> Comment
ListCommentController --> Comment
EditCommentController --> Comment
DeleteCommentController --> Comment

@enduml